### ISSUE TITLE
Should all 'open in colab' buttons be removed in docs/*

### ISSUE THREAD

**Issue by windmaple** [jax-ml/jax-ai-stack#122]
Some notebooks have these buttons; most don't. Btw, these buttons are broken, now that the notebooks are moved into 'source' subfolder.

**Comment by jakevdp** [comment]
Thanks for the note – I've been planning to go through and regularlize things like this once we merge all the docs. For what it's worth, I think we should keep these buttons, fix the urls, and add them where missing.

**Comment by vfdev-5** [comment]
Reordering the tutorials by topic would be nice as well
